engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 56

  markdownlint:
    enabled: true
    checks:
      MD002: # Requires first header to be top level
        enabled: false
      MD033: # Checks for inline HTML
        enabled: false

  fixme:
    enabled: true

  pep8:
    enabled: true
    checks:
      E731: # Suggests def instead of lambda
        enabled: false

  radon: 
    enabled: true
    config: 
      threshold: "C"

ratings:
  paths:
  - "**.md"    
  - "**.py"

exclude_patterns:
    - "docs/_build/"
    - "cmd_line.py"
