#!/usr/bin/env bash

# Build the package
python setup.py sdist
python setup.py bdist_wheel --universal

read -p "Ready to upload to PyPi. Proceed? (y/n)
" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    # Upload package and remove local build files
    twine upload dist/*
fi

echo "Removing build files..."
rm -r build
rm -r dist
rm -r pwv_kpno.egg-info
rm -r pwv_kpno-*